# Generated by Django 4.0.4 on 2022-06-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_created_postlikes_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlikes',
            options={'verbose_name_plural': 'Post Likes'},
        ),
    ]
