# Generated by Django 4.0.4 on 2022-06-11 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_story_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 11, 5, 7, 694553)),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_image',
            field=models.ImageField(null=True, upload_to='stories/'),
        ),
    ]
