# Generated by Django 4.0.4 on 2022-06-11 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_story_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 11, 6, 34, 880627)),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_image',
            field=models.ImageField(upload_to='stories/'),
        ),
    ]
