# Generated by Django 4.0.4 on 2022-06-11 11:35

import datetime
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_story_expiration_date_alter_story_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 11, 35, 4, 254383)),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=50, size=[500, 300], upload_to='stories/'),
        ),
    ]
