# Generated by Django 4.0.4 on 2022-06-12 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_remove_storycategory_story_story_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storycategory',
            options={'verbose_name_plural': 'Story Categories'},
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 16, 25, 25, 947664)),
        ),
    ]
