# Generated by Django 4.0.4 on 2022-06-07 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
    ]
