# Generated by Django 4.0.4 on 2022-06-09 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_alter_messagemodel_date_alter_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
