# Generated by Django 4.0.4 on 2022-06-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_storycategory_options_and_more'),
        ('accounts', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryViewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
