# Generated by Django 4.0.4 on 2022-06-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_storyviewsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoryViewsModel',
        ),
    ]
